export enum ENUM_AUTH_TOPICS {
  SIGN_IN = 'SIGN_IN',
  SIGN_UP = 'SIGN_UP',
  SIGN_OUT = 'SIGN_OUT',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
}

export enum ENUM_USER_TOPICS {
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
  FIND_ALL_USERS = 'FIND_ALL_USERS',
  FIND_USER_BY_USERNAME = 'FIND_USER_BY_USERNAME',
  FIND_USER_BY_EMAIL = 'FIND_USER_BY_EMAIL',
  FIND_USER_BY_PHONE = 'FIND_USER_BY_PHONE',
  FIND_USER_BY_ID = 'FIND_USER_BY_ID',
}

export const AllTopics = {
  ...ENUM_AUTH_TOPICS,
  ...ENUM_USER_TOPICS,
};
